import type { Metadata } from 'next';
import { Gowun_Batang } from 'next/font/google';
import './globals.css';

const gownu = Gowun_Batang({
  subsets: ['latin'],
  weight: ['400', '700'],
});
// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "I'm here",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko-KR'>
      <body className={gownu.className}>{children}</body>
    </html>
  );
}
